name: 'Cosmos Gosec Security Checker'
description: 'Runs the gosec security checker'
author: 'Cosmos Ecosystem'

inputs:
  args:
    description: 'Arguments for gosec'
    required: true
    default: '-h'

runs:
    using: 'docker'
    image: 'docker://ghcr.io/cosmos/gosec'
    args:
      - ${{ inputs.args }}

branding:
  icon: 'shield'
  color: 'blue'
