name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        go_version:
          - '1.17'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Setup go ${{ matrix.go_version }} 
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Checkout Source 
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Tests
        run: make test
  coverage:
    needs: tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Checkout Source 
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Create Test Coverage
        run: make test-coverage
      - name: Upload Test Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
